using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KenseiECS.Generators {
    /// <summary>
    /// For every partial class with [Inc]/[Exc]/[Any]/[Pool]/[Group]/[Shared]
    /// fields, emits an IInitSystem.Init that fills those fields from the
    /// World and SharedData and then calls partial void OnInit(world, shared).
    /// </summary>
    [Generator]
    public sealed class SystemInjectionGenerator : ISourceGenerator {
        private const string IncAttribute = "KenseiECS.IncAttribute";
        private const string ExcAttribute = "KenseiECS.ExcAttribute";
        private const string AnyAttribute = "KenseiECS.AnyAttribute";
        private const string PoolAttribute = "KenseiECS.PoolAttribute";
        private const string GroupAttribute = "KenseiECS.GroupAttribute";
        private const string SharedAttribute = "KenseiECS.SharedAttribute";

        private static readonly DiagnosticDescriptor NotPartial = new(
            "KECS001", "System class must be partial",
            "Class '{0}' has injected fields but is not declared partial; add the partial modifier so Init can be generated",
            "KenseiECS", DiagnosticSeverity.Error, true);

        private static readonly DiagnosticDescriptor InitAlreadyDeclared = new(
            "KECS002", "Init is generated",
            "Class '{0}' declares Init(World, SharedData) and also has injected fields; remove Init and put custom setup into 'partial void OnInit(World world, SharedData shared)'",
            "KenseiECS", DiagnosticSeverity.Error, true);

        private static readonly DiagnosticDescriptor WrongFieldType = new(
            "KECS003", "Injected field has an unexpected type",
            "Field '{0}' is marked [{1}] but its type is '{2}'; expected {3}",
            "KenseiECS", DiagnosticSeverity.Error, true);

        private static readonly DiagnosticDescriptor ContainerNotPartial = new(
            "KECS005", "Containing type must be partial",
            "Class '{0}' is nested in '{1}', which is not declared partial; add the partial modifier to every containing type",
            "KenseiECS", DiagnosticSeverity.Error, true);

        private static readonly DiagnosticDescriptor FilterWithoutInc = new(
            "KECS004", "Filter needs Inc or Any",
            "Filter field '{0}' has [Exc] without [Inc] or [Any]; exclude-only filters are not supported",
            "KenseiECS", DiagnosticSeverity.Error, true);

        private static readonly SymbolDisplayFormat Qualified = SymbolDisplayFormat.FullyQualifiedFormat;

        public void Initialize(GeneratorInitializationContext context) {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context) {
            if (!(context.SyntaxReceiver is Receiver receiver)) {
                return;
            }

            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var classDecl in receiver.Candidates) {
                var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
                if (!(model.GetDeclaredSymbol(classDecl) is INamedTypeSymbol symbol) || !seen.Add(symbol)) {
                    continue;
                }
                Generate(context, symbol, classDecl);
            }
        }

        private static void Generate(GeneratorExecutionContext context, INamedTypeSymbol symbol, ClassDeclarationSyntax classDecl) {
            var fields = CollectFields(context, symbol);
            if (fields.Count == 0) {
                return;
            }

            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword)) {
                context.ReportDiagnostic(Diagnostic.Create(NotPartial, classDecl.Identifier.GetLocation(), symbol.Name));
                return;
            }

            foreach (var member in symbol.GetMembers("Init").OfType<IMethodSymbol>()) {
                if (member.Parameters.Length == 2 && !member.IsImplicitlyDeclared && member.Locations.Any(l => l.IsInSource)) {
                    context.ReportDiagnostic(Diagnostic.Create(InitAlreadyDeclared, member.Locations[0], symbol.Name));
                    return;
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated by KenseiECS.Generators />");
            sb.AppendLine("#nullable disable");

            string ns = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();
            int indent = 0;
            if (ns != null) {
                sb.AppendLine($"namespace {ns} {{");
                indent++;
            }

            var containers = new List<INamedTypeSymbol>();
            for (var outer = symbol.ContainingType; outer != null; outer = outer.ContainingType) {
                if (!IsDeclaredPartial(outer)) {
                    context.ReportDiagnostic(Diagnostic.Create(ContainerNotPartial, classDecl.Identifier.GetLocation(), symbol.Name, outer.Name));
                    return;
                }
                containers.Insert(0, outer);
            }
            foreach (var container in containers) {
                string modifiers = container.IsStatic ? "static partial" : "partial";
                sb.AppendLine($"{Pad(indent)}{modifiers} {Keyword(container)} {container.Name}{TypeParameters(container)} {{");
                indent++;
            }

            bool implementsInit = symbol.AllInterfaces.Any(i => i.ToDisplayString() == "KenseiECS.IInitSystem");
            string baseList = implementsInit ? "" : " : global::KenseiECS.IInitSystem";
            sb.AppendLine($"{Pad(indent)}partial class {symbol.Name}{TypeParameters(symbol)}{baseList} {{");
            indent++;

            sb.AppendLine($"{Pad(indent)}partial void OnInit(global::KenseiECS.World world, global::KenseiECS.SharedData shared);");
            sb.AppendLine();
            sb.AppendLine($"{Pad(indent)}public void Init(global::KenseiECS.World world, global::KenseiECS.SharedData shared) {{");
            indent++;
            foreach (var line in fields) {
                sb.AppendLine($"{Pad(indent)}{line}");
            }
            sb.AppendLine($"{Pad(indent)}OnInit(world, shared);");
            indent--;
            sb.AppendLine($"{Pad(indent)}}}");

            while (indent > 0) {
                indent--;
                sb.AppendLine($"{Pad(indent)}}}");
            }

            string hint = symbol.ToDisplayString().Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
            context.AddSource($"{hint}.Injection.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static List<string> CollectFields(GeneratorExecutionContext context, INamedTypeSymbol symbol) {
            var lines = new List<string>();
            foreach (var field in symbol.GetMembers().OfType<IFieldSymbol>()) {
                if (field.IsStatic) {
                    continue;
                }

                AttributeData inc = null, exc = null, any = null, pool = null, group = null, shared = null;
                foreach (var attribute in field.GetAttributes()) {
                    string name = attribute.AttributeClass?.ToDisplayString();
                    switch (name) {
                        case IncAttribute: inc = attribute; break;
                        case ExcAttribute: exc = attribute; break;
                        case AnyAttribute: any = attribute; break;
                        case PoolAttribute: pool = attribute; break;
                        case GroupAttribute: group = attribute; break;
                        case SharedAttribute: shared = attribute; break;
                    }
                }

                string fieldType = field.Type.ToDisplayString();
                if (inc != null || exc != null || any != null) {
                    if (fieldType != "KenseiECS.Filter") {
                        Report(context, field, WrongFieldType, "Inc/Exc/Any", "KenseiECS.Filter");
                        continue;
                    }
                    if (inc == null && any == null) {
                        context.ReportDiagnostic(Diagnostic.Create(FilterWithoutInc, field.Locations[0], field.Name));
                        continue;
                    }
                    var call = new StringBuilder("world.Filter()");
                    AppendTypeCalls(call, "Inc", inc);
                    AppendTypeCalls(call, "Exc", exc);
                    AppendTypeCalls(call, "Any", any);
                    call.Append(".End()");
                    lines.Add($"this.{field.Name} = {call};");
                } else if (pool != null) {
                    if (!(field.Type is INamedTypeSymbol named) || named.ConstructedFrom.ToDisplayString() != "KenseiECS.ComponentPool<T>") {
                        Report(context, field, WrongFieldType, "Pool", "KenseiECS.ComponentPool<T>");
                        continue;
                    }
                    lines.Add($"this.{field.Name} = world.Pool<{named.TypeArguments[0].ToDisplayString(Qualified)}>();");
                } else if (group != null) {
                    if (!(field.Type is INamedTypeSymbol named) || !named.ConstructedFrom.ToDisplayString().StartsWith("KenseiECS.Group<")) {
                        Report(context, field, WrongFieldType, "Group", "KenseiECS.Group<...>");
                        continue;
                    }
                    string args = string.Join(", ", named.TypeArguments.Select(t => t.ToDisplayString(Qualified)));
                    lines.Add($"this.{field.Name} = world.Group<{args}>();");
                } else if (shared != null) {
                    string key = shared.ConstructorArguments.Length > 0 && shared.ConstructorArguments[0].Value is string s
                        ? $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\""
                        : null;
                    string typeName = field.Type.ToDisplayString(Qualified);
                    lines.Add(key == null
                        ? $"this.{field.Name} = shared.Get<{typeName}>();"
                        : $"this.{field.Name} = shared.Get<{typeName}>({key});");
                }
            }
            return lines;
        }

        private static void AppendTypeCalls(StringBuilder call, string method, AttributeData attribute) {
            if (attribute == null || attribute.ConstructorArguments.Length == 0) {
                return;
            }
            foreach (var value in attribute.ConstructorArguments[0].Values) {
                if (value.Value is ITypeSymbol type) {
                    call.Append('.').Append(method).Append('<').Append(type.ToDisplayString(Qualified)).Append(">()");
                }
            }
        }

        private static void Report(GeneratorExecutionContext context, IFieldSymbol field, DiagnosticDescriptor descriptor, string attribute, string expected) {
            context.ReportDiagnostic(Diagnostic.Create(descriptor, field.Locations[0], field.Name, attribute, field.Type.ToDisplayString(), expected));
        }

        private static bool IsDeclaredPartial(INamedTypeSymbol type) {
            foreach (var reference in type.DeclaringSyntaxReferences) {
                if (reference.GetSyntax() is TypeDeclarationSyntax declaration && declaration.Modifiers.Any(SyntaxKind.PartialKeyword)) {
                    return true;
                }
            }
            return false;
        }

        private static string Keyword(INamedTypeSymbol type) {
            return type.TypeKind == TypeKind.Struct ? "struct" : "class";
        }

        private static string TypeParameters(INamedTypeSymbol type) {
            return type.TypeParameters.Length == 0
                ? ""
                : "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";
        }

        private static string Pad(int indent) {
            return new string(' ', indent * 4);
        }

        private sealed class Receiver : ISyntaxReceiver {
            private static readonly HashSet<string> Names = new() {
                "Inc", "Exc", "Any", "Pool", "Group", "Shared",
                "IncAttribute", "ExcAttribute", "AnyAttribute", "PoolAttribute", "GroupAttribute", "SharedAttribute"
            };

            public List<ClassDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node) {
                if (!(node is FieldDeclarationSyntax field) || field.AttributeLists.Count == 0) {
                    return;
                }
                foreach (var list in field.AttributeLists) {
                    foreach (var attribute in list.Attributes) {
                        string name = attribute.Name is QualifiedNameSyntax q ? q.Right.Identifier.Text : attribute.Name.ToString();
                        if (Names.Contains(name) && field.Parent is ClassDeclarationSyntax owner) {
                            Candidates.Add(owner);
                            return;
                        }
                    }
                }
            }
        }
    }
}
