import { existsSync, readFileSync } from 'node:fs'
import { defineConfig, type DefaultTheme } from 'vitepress'

const repo = 'https://github.com/KenseiTheOne/KenseiECS'

// Generated by `npm run gen:api` (docs/scripts/gen-api.mjs); absent until then,
// in which case the API section only has the hand-written overview page.
const apiSidebarFile = new URL('../api/sidebar.json', import.meta.url)
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(apiSidebarFile)
  ? JSON.parse(readFileSync(apiSidebarFile, 'utf8'))
  : [{ text: 'API Reference', items: [{ text: 'Overview', link: '/api/' }] }]

export default defineConfig({
  title: 'KenseiECS',
  description: 'Lightweight sparse-set ECS for Unity and .NET',
  base: '/KenseiECS/',
  cleanUrls: true,
  lastUpdated: true,
  // The repo-level docs index is for GitHub browsing; the site has its own home page.
  srcExclude: ['README.md', 'snippets/**'],
  // /demo/ is the Horde WebAssembly build, copied into dist/demo/ by the Pages
  // workflow after the VitePress build; it is not a VitePress page.
  ignoreDeadLinks: [/^\/demo(\/|$)/],
  head: [['link', { rel: 'icon', href: '/KenseiECS/favicon.svg' }]],
  markdown: {
    theme: { light: 'github-light', dark: 'github-dark' },
    config(md) {
      // The permalink's aria-label ("Permalink to ...") is built from the heading's
      // raw Markdown, so API headings like `<a id="..."></a> Class ComponentPool&lt;T\>`
      // leaked markup into it. Reduce the heading source to its text first.
      md.core.ruler.before('anchor', 'heading-plain-text', (state) => {
        state.tokens.forEach((token, i) => {
          if (token.type !== 'heading_open') return
          const inline = state.tokens[i + 1]
          if (!inline?.children) return
          inline.content = md.utils.unescapeAll(
            inline.children
              .filter((t) => t.type === 'text' || t.type === 'code_inline')
              .map((t) => t.content)
              .join('')
              .trim(),
          )
        })
      })
    },
  },
  themeConfig: {
    logo: '/favicon.svg',
    nav: [
      { text: 'Guide', link: '/guide/introduction', activeMatch: '/(guide/(?!demo|comparison)|concepts/|guides/)' },
      { text: 'Unity', link: '/unity/bootstrap', activeMatch: '/unity/' },
      { text: 'Live Demo', link: '/guide/demo' },
      { text: 'API', link: '/api/', activeMatch: '/api/' },
      { text: 'Reference', activeMatch: '/(architecture|benchmarks|guide/comparison|faq|migration-from-leoecslite|changelog|contributing)', items: [
        { text: 'Benchmarks', link: '/benchmarks' },
        { text: 'Comparison', link: '/guide/comparison' },
        { text: 'Architecture', link: '/architecture' },
        { text: 'Migrating from LeoEcsLite', link: '/migration-from-leoecslite' },
        { text: 'FAQ', link: '/faq' },
        { text: 'Contributing', link: '/contributing' },
      ] },
      { text: 'v2.0.0', items: [
        { text: 'Changelog', link: '/changelog' },
        { text: 'Releases', link: `${repo}/releases` },
      ] },
    ],
    sidebar: {
      '/api/': apiSidebar,
      '/': [
        { text: 'Getting Started', collapsed: false, items: [
          { text: 'Introduction', link: '/guide/introduction' },
          { text: 'Installation', link: '/guide/installation' },
          { text: 'Quick Start', link: '/guide/quick-start' },
          { text: 'Live Demo', link: '/guide/demo' },
          { text: 'Inside the Demo', link: '/guide/inside-the-demo' },
        ] },
        { text: 'Core Concepts', collapsed: false, items: [
          { text: 'Entities', link: '/concepts/entities' },
          { text: 'Components', link: '/concepts/components' },
          { text: 'Filters', link: '/concepts/filters' },
          { text: 'Systems & SharedData', link: '/concepts/systems' },
          { text: 'SystemsRunner', link: '/concepts/runner' },
        ] },
        { text: 'Features', collapsed: true, items: [
          { text: 'Groups', link: '/guides/groups' },
          { text: 'Change Tracking', link: '/guides/change-tracking' },
          { text: 'CommandBuffer', link: '/guides/command-buffer' },
          { text: 'Singletons', link: '/guides/singletons' },
          { text: 'OneFrame Components', link: '/guides/one-frame' },
          { text: 'Component Listeners', link: '/guides/component-listeners' },
          { text: 'World Events', link: '/guides/world-events' },
          { text: 'World Lifecycle', link: '/guides/world-lifecycle' },
          { text: 'Snapshots', link: '/guides/snapshots' },
          { text: 'Generated Init', link: '/guides/source-generator' },
          { text: 'Threading', link: '/guides/threading' },
          { text: 'WorldConfig', link: '/guides/world-config' },
          { text: 'Release vs. KENSEI_DEBUG', link: '/guides/debug-mode' },
        ] },
        { text: 'Unity', collapsed: true, items: [
          { text: 'Bootstrap & Authoring', link: '/unity/bootstrap' },
          { text: 'EcsEntityView', link: '/unity/entity-view' },
          { text: 'Listener Bridge', link: '/unity/listener-bridge' },
          { text: 'Debug Tools', link: '/unity/debug-tools' },
          { text: 'BasicGame Sample', link: '/unity/sample' },
        ] },
        { text: 'Reference', collapsed: true, items: [
          { text: 'Architecture', link: '/architecture' },
          { text: 'Benchmarks', link: '/benchmarks' },
          { text: 'Comparison', link: '/guide/comparison' },
          { text: 'Migrating from LeoEcsLite', link: '/migration-from-leoecslite' },
          { text: 'FAQ', link: '/faq' },
          { text: 'Changelog', link: '/changelog' },
          { text: 'Contributing', link: '/contributing' },
          { text: 'API Reference', link: '/api/' },
        ] },
      ],
    },
    socialLinks: [{ icon: 'github', link: repo }],
    editLink: { pattern: `${repo}/edit/main/docs/:path` },
    search: { provider: 'local' },
    outline: { level: [2, 3] },
    footer: {
      message: [
        '<a href="/KenseiECS/guide/introduction">Guide</a>',
        '<a href="/KenseiECS/guide/demo">Live Demo</a>',
        '<a href="/KenseiECS/benchmarks">Benchmarks</a>',
        '<a href="/KenseiECS/changelog">Changelog</a>',
        `<a href="${repo}">GitHub</a>`,
      ].join(' · '),
      copyright: 'Released under the MIT License.',
    },
  },
})
